#Server
server:
  port: 8081
  servlet:
    context-path: /ms-atividades/v1

# Datasource
spring:
  data:
    mongodb:
      database: ${SPRING_DATA_MONGODB_MS_ATIVIDADES_DATABASE:ms_atividades}
      host: ${SPRING_DATA_MS_ATIVIDADES_HOST:mongodb-ms-atividades}
      port: ${SPRING_DATA_MS_ATIVIDADES_PORT:27017}




