CREATE TABLE empresa (
    id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    codigo BIGINT(5) NOT NULL UNIQUE,
    cnpj VARCHAR(20) NOT NULL UNIQUE,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    telefone VARCHAR(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
