# Server
server:
  port: 8082
  servlet:
    context-path: /ms-analytics/v1


# Redis
spring:
  redis:
    host: redis
    port: 6379
    password: redis
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
      shutdown-timeout: 200ms

